### ISSUE TITLE
Reduce npm package size

### ISSUE THREAD

**Issue by Aarbel** [dherault/react-apple-emojis#11]
![image](https://user-images.githubusercontent.com/25119847/124975224-188ddd80-e02e-11eb-9f8c-af224ed77a87.png)

For a library that just roots to external links, looks that's really heavy ;)

**Comment by Aarbel** [comment]
You should really compress this file, it's only 3000 lines, and all urls start with `https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/apple/237/`

https://github.com/dherault/react-apple-emojis/blob/master/src/data.json

**Comment by Aarbel** [comment]
Just saved 200kb doing that

![image](https://user-images.githubusercontent.com/25119847/124976384-7d960300-e02f-11eb-8a66-7ac819c9f29a.png)

**Comment by Aarbel** [comment]
Removing .png at the end of each value 

![image](https://user-images.githubusercontent.com/25119847/124976765-f7c68780-e02f-11eb-8787-40ed722475b5.png)

**Comment by Aarbel** [comment]
In addition to that you can remove all the values which match the keys.
So that if the values starts with and underscore "_", let's add the key in front of it to build its url

![image](https://user-images.githubusercontent.com/25119847/124976919-26446280-e030-11eb-8a88-c85079949b5a.png)

**Comment by Aarbel** [comment]
I guess you will again save a lot

**Comment by dherault** [comment]
I'll try to! I'm on it.

**Comment by dherault** [comment]
So, the package size got bigger actually ^^

You can reduce it by using your own CDN for images, see the README.
