### ISSUE TITLE
Is it possible to convert windows emoji to apple emoji using your library?

### ISSUE THREAD

**Issue by vadymchornyidev** [dherault/react-apple-emojis#23]
**I work on Windows**, I write posts in the project through **markdown**, <br>
I insert **Windows emoji** there, <br>
**I would like to convert emoji to apple style at the output in markdown files**, <br>
**as Telegram does**

**GIF how it works in Telegram**
https://imgur.com/a/dq2fzTq

**My code where I convert markdown to html**
https://github.com/1alexvash/AlexCodeBlog/blob/master/helpers/markdownToHtml.ts

**Comment by alfawal** [comment]
its not, this library is just wrapping the emojis from emojipedia as a react component and is not capable of doing such thing.

**Comment by dherault** [comment]
Correct, closing.
