### ISSUE TITLE
Urls stop working

### ISSUE THREAD

**Issue by alacret** [dherault/react-apple-emojis#25]
https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/72/apple/285/flushed-face_1f633.png

**Comment by Expensiveee** [comment]
Not fixing this?

**Comment by dherault** [comment]
If anyone has a good emoji URL list on a correct CDN please tell me.

**Comment by Codemaine** [comment]
@dherault Check this out. You can go to each icon's page, and Copy the image link of the previews: https://emojipedia.org/apple

**Comment by dherault** [comment]
I changed the data file, should be good now
